# SPDX-FileCopyrightText: 2023 XWiki CryptPad Team <contact@cryptpad.org> and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
services:
  cryptpad:
    image: "cryptpad/cryptpad:version-2025.3.0"
    hostname: cryptpad

    environment:
      - CPAD_MAIN_DOMAIN=https://${CPAD_MAIN_DOMAIN}
      - CPAD_SANDBOX_DOMAIN=https://${CPAD_SANDBOX_DOMAIN}
      - CPAD_CONF=/cryptpad/config/config.js
      - CPAD_INSTALL_ONLYOFFICE=${CPAD_INSTALL_ONLYOFFICE}

    volumes:
      - ./data/blob:/cryptpad/blob
      - ./data/block:/cryptpad/block
      - ./customize:/cryptpad/customize
      - ./data/data:/cryptpad/data
      - ./data/files:/cryptpad/datastore
      - ./onlyoffice-dist:/cryptpad/www/common/onlyoffice/dist
      - ./onlyoffice-conf:/cryptpad/onlyoffice-conf
      - ./config/config.js:/cryptpad/config/config.js

    ports:
      - "3000:3000"
      - "3003:3003"

    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.cryptpad-prod-https.rule=Host(`${CPAD_MAIN_DOMAIN}`) && PathPrefix(`/`)'
      - traefik.http.routers.cryptpad-prod-https.entryPoints=https
      - traefik.http.routers.cryptpad-prod-https.middlewares=gzip
      - traefik.http.routers.cryptpad-prod-https.service=cryptpad-prod
      - traefik.http.routers.cryptpad-prod-https.tls=true
      - traefik.http.services.cryptpad-prod.loadbalancer.server.port=3000
      - traefik.http.routers.cryptpad-prod-https.tls.certresolver=letsencrypt
      - 'traefik.http.routers.cryptpad-prod-http.rule=Host(`${CPAD_MAIN_DOMAIN}`) && PathPrefix(`/`)'
      - traefik.http.routers.cryptpad-prod-http.entryPoints=http
      - traefik.http.routers.cryptpad-prod-http.middlewares=redirect-to-https
      - 'traefik.http.routers.cryptpad-test-https.rule=Host(`${CPAD_SANDBOX_DOMAIN}`) && PathPrefix(`/`)'
      - traefik.http.routers.cryptpad-test-https.entryPoints=https
      - traefik.http.routers.cryptpad-test-https.middlewares=gzip
      - traefik.http.routers.cryptpad-test-https.service=cryptpad-test
      - traefik.http.routers.cryptpad-test-https.tls=true
      - traefik.http.services.cryptpad-test.loadbalancer.server.port=3003
      - traefik.http.routers.cryptpad-test-https.tls.certresolver=letsencrypt
      - 'traefik.http.routers.cryptpad-test-http.rule=Host(`${CPAD_SANDBOX_DOMAIN}`) && PathPrefix(`/`)'
      - traefik.http.routers.cryptpad-test-http.entryPoints=http
      - traefik.http.routers.cryptpad-test-http.middlewares=redirect-to-https
      
